<?php
include "shape.php";
class retangle extends Shape{
    public function __construct($side1, $side2, $side3)
    {
        parent::__construct($side1, $side2, $side3);
    }
    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}
